AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Resolves top level dependencies into package weights map and persists to S3
Parameters:
  MongoUri:
    Type: AWS::SSM::Parameter::Value<String>
    Default: '/api/db/mongo_uri'
Resources:
  OrgRegistryResolverDeadLetterQueue:
    Type: AWS::SQS::Queue
  OrgRegistryResolverQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: org-registry-resolver-input
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt OrgRegistryResolverDeadLetterQueue.Arn
        maxReceiveCount: 3
      VisibilityTimeout: 960
  OrgRegistryResolverFunction:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 900
      MemorySize: 2048
      Handler: index.handler
      Runtime: nodejs12.x
      CodeUri: ./
      Events:
        OrgRegistryResolverEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt OrgRegistryResolverQueue.Arn
            BatchSize: 1
      Policies:
        - AmazonSQSFullAccess
        - AmazonDynamoDBFullAccess
        - AmazonS3FullAccess
        - Statement:
          - Effect: Allow
            Action:
              - 'kms:Decrypt'
              - 'kms:ListKeys'
            Resource: '*'
      Environment:
        Variables:
          MONGO_URI: !Ref MongoUri
